org: mercerccw
app: claytonmercer-projects
# serverless.yml

service: claytonmercer-projects

provider:
  name: aws
  runtime: nodejs12.x
  stage: production
  region: us-east-2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'